### ISSUE TITLE
[Feature Suggestion] Support decompiler based on Renpy 5.x games

### ISSUE THREAD

**Issue by jwcloverain** [CensoredUsername/unrpyc#167]
Here rpyc file
[script.rpyc](https://github.com/jwcloverain/jwbkup/blob/master/script.rpyc)

Full Traceback:
```
Decompiling script.rpyc to script.rpy...
Error while decompiling script.rpyc:
Traceback (most recent call last):
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\unrpyc.py", line 202, in worker
    tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\unrpyc.py", line 174, in decompile_rpyc
    init_offset=init_offset)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 46, in pprint
    decompile_python=decompile_python, translator=translator).dump(ast, indent_level, init_offset, tag_outside_block)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 116, in dump
    super(Decompiler, self).dump(ast, indent_level, skip_indent_until_write=True)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\util.py", line 29, in dump
    self.print_nodes(ast)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\util.py", line 120, in print_nodes
    self.print_node(node)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 133, in print_node
    self.dispatch.get(type(ast), type(self).print_unknown)(self, ast)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 643, in print_init
    self.print_nodes(ast.block, 1)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\util.py", line 120, in print_nodes
    self.print_node(node)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 133, in print_node
    self.dispatch.get(type(ast), type(self).print_unknown)(self, ast)
  File "C:\Users\Jason Wu\Desktop\unrpyc-master\unrpyc-master\decompiler\__init__.py", line 735, in print_python
    code = ast.code.source
AttributeError: 'Python' object has no attribute 'code'
Decompilation of 1 file failed
```

**Comment by madeddy** [comment]
**Most important infos are missing. See:** 
https://github.com/CensoredUsername/unrpyc#when-making-an-issue-report

Nobody of us has a crystal orb to divine such things.
