### ISSUE TITLE
AttributeError: 'RevertableList' object has no attribute 'append'

### ISSUE THREAD

**Issue by DinakiS** [CensoredUsername/unrpyc#169]
Hello.
I'm using the latest unrpyc version by @madeddy to online decompile .rpyc files here: https://gameresourcesviewer.ru/

Some files throws this error:
```
Traceback (most recent call last):
  File "/home/pyodide/unrpyc/__init__.py", line 190, in decompile_rpyc
    ast = read_ast_from_file(in_file)
  File "/home/pyodide/unrpyc/__init__.py", line 163, in read_ast_from_file
    data, stmts = revertable_switch(raw_contents)
  File "/home/pyodide/unrpyc/__init__.py", line 132, in revertable_switch
    data, stmts = magic.safe_loads(raw_dat, cls_factory_74, {
  File "/home/pyodide/unrpyc/decompiler/magic.py", line 604, in safe_loads
    return SafeUnpickler(StringIO(string), class_factory, safe_modules, use_copyreg,
  File "/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/lib/python3.9/pickle.py", line 1664, in load_append
    list.append(value)
AttributeError: 'RevertableList' object has no attribute 'append'
```

Unfortunately I don't know the Ren'Py version, but I have a .rpyc file that throws this error.
[problem_rpyc.zip](https://github.com/CensoredUsername/unrpyc/files/11454002/problem_rpyc.zip)

**Comment by madeddy** [comment]
I did test it and got no problems:
```shell
$ python3 ~/Code/Git/unrpyc/unrpyc.py /home/olli/Code/tst_apps/problem.rpyc
Decompiling /home/olli/Code/tst_apps/problem.rpyc to /home/olli/Code/tst_apps/problem.rpy...
Decompilation of 1 script file successful
```
I used the branch for renpy v8.0.x versions: https://github.com/madeddy/unrpyc/tree/py3_v1.1.8

> Unfortunately I don't know the Ren'Py version...

The version can be found in the files:
- .../game_name/game/script_version.txt
- .../game_name/log.txt (line 3)
- .../game_name/renpy/init.py (section "version information", lines after 68)

**Comment by DinakiS** [comment]
Turns out I was using the wrong branch (https://github.com/madeddy/unrpyc/tree/Renpy_8_7.5_compat_fix%40v1.1.8)
Switching to the https://github.com/madeddy/unrpyc/tree/py3_v1.1.8 solves the problem.
Thank you.

**Comment by madeddy** [comment]
> Turns out I was using the wrong branch...

Probably my fault naming them like this and people do very likely not get was the intend and reason is. They need this separate so the unrpyc main devs see what i did in every area. e.g.

- Code for py3 porting
- fixes for new renpy
- fix for a certain bug
- and all this mixed for certain renpy versions
