### ISSUE TITLE
windows 10: "revertabledict doesnt support item assignment

### ISSUE THREAD

**Issue by sI1vre** [CensoredUsername/unrpyc#170]
on windows 10. game is renpy ver 7.6.0. rpaextract works perfectly on it, so i dont know what the issue could be

```
Failed at decompiling C:\Users\Owner\Downloads\SouthScrimshaw-1.0-pc\SouthScrimshaw-1.0-pc\game\script.rpyc
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1212, in load_setitems
TypeError: 'RevertableDict' object does not support item assignment
```

every file has the exact same error

**Comment by awcator** [comment]
Check this workaround. At least, for me this is working
https://github.com/CensoredUsername/unrpyc/issues/156

**Comment by madeddy** [comment]
This is resolved in https://github.com/CensoredUsername/unrpyc/pull/161

**Comment by CensoredUsername** [comment]
Should be fixed in the current release, please reopen if it isn't.
