### ISSUE TITLE
Safepickler in Py3 possibly broken

### ISSUE THREAD

**Issue by madeddy** [CensoredUsername/unrpyc#216]
With Linux, Python 3.10 and Ren'py 8.2.0 app.
I tested something with the TL feature and noticed this problem:

```bash
olli@tty2*blue $ python ~/Code/Git/unrpyc/unrpyc.py ~/.xlib/RPG/_test/OurBrightDays-0.1.3-pc/game -T /home/olli/.xlib/RPG/_test/OurBrightDays-0.1.3-pc/game/tl/tl.txt -l english -c

_...(Nearly 500 files ommited)..._

Error while decompiling /home/olli/.xlib/RPG/_test/OurBrightDays-0.1.3-pc/game/tl/english/scripts/00parts/01arrival/03script/script.rpyc:
Traceback (most recent call last):
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-2.0.1/unrpyc.py", line 218, in worker
return extract_translations(filename, args.language)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-2.0.1/unrpyc.py", line 177, in extract_translations
return pickle_safe_dumps(translator.dialogue), translator.strings
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-2.0.1/decompiler/renpycompat.py", line 168, in pickle_safe_dumps
return magic.safe_dumps(buffer)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-2.0.1/decompiler/magic.py", line 639, in safe_dumps
SafePickler(file, protocol).dump(obj)
File "/usr/lib/python3.10/pickle.py", line 487, in dump
self.save(obj)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 932, in save_list
self._batch_appends(obj)
File "/usr/lib/python3.10/pickle.py", line 959, in _batch_appends
save(tmp[0])
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 687, in save_reduce
save(cls)
File "/usr/lib/python3.10/pickle.py", line 572, in save
self.save_global(obj)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-2.0.1/decompiler/magic.py", line 548, in save_global
self.write(STACK_GLOBAL)
NameError: name 'STACK_GLOBAL' is not defined
```
There where 25 files with this error. The fix looked easy, as the module prefix is just missing: `self.write(pickle.STACK_GLOBAL)` instead of `self.write(STACK_GLOBAL)`

However the next run with the fix...this happened:
```
Error while decompiling /home/olli/.xlib/RPG/_test/OurBrightDays-0.1.3-pc/game/tl/english/scripts/00parts/01arrival/03script/script.rpyc:
Traceback (most recent call last):
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 218, in worker
return extract_translations(filename, args.language)
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 177, in extract_translations
return pickle_safe_dumps(translator.dialogue), translator.strings
File "/home/olli/Code/Git/unrpyc/decompiler/renpycompat.py", line 168, in pickle_safe_dumps
return magic.safe_dumps(buffer)
File "/home/olli/Code/Git/unrpyc/decompiler/magic.py", line 639, in safe_dumps
SafePickler(file, protocol).dump(obj)
File "/usr/lib/python3.10/pickle.py", line 487, in dump
self.save(obj)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 932, in save_list
self._batch_appends(obj)
File "/usr/lib/python3.10/pickle.py", line 959, in _batch_appends
save(tmp[0])
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
save(state)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
save(state)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 691, in save_reduce
save(func)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 1129, in save_type
return self.save_global(obj)
File "/home/olli/Code/Git/unrpyc/decompiler/magic.py", line 556, in save_global
pickle.Pickler.save_global(self, obj, name, pack)
AttributeError: type object '_pickle.Pickler' has no attribute 'save_global'
```
This time 8 files with the second error. I can atm not search for this and it makes surely more sense to you.

[scripts.zip](https://github.com/CensoredUsername/unrpyc/files/14844779/scripts.zip)

**Comment by CensoredUsername** [comment]
Ah, I have an idea what the issue is, I'll look at it.

**Comment by madeddy** [comment]
Very good.
I checked `pickle_Pickler` and the supposedly missing method is there. Same in the c module, as far as my understanding there goes. I draw a blank with this. If you have it, i would appreciate a short explanation.

**Comment by CensoredUsername** [comment]
The one in the c module is only an internal c function. It doesn't export it as a method on the Pickler object. That's why you don't see it.

```python
>>> _pickle.Pickler.save_global
AttributeError: type object '_pickle.Pickler' has no attribute 'save_global'
```

Outside of that, calling it with a pack kwarg is an internal py2 thing that we shouldn't be doing to begin with as well.

I think the fixed code would be:

```python
    def save_global(self, obj, name=None, pack=struct.pack):
        if isinstance(obj, FakeClassType):
            if PY2:
                self.write(pickle.GLOBAL + obj.__module__ + '\n' + obj.__name__ + '\n')
            elif self.proto >= 4:
                self.save(obj.__module__)
                self.save(obj.__name__)
                self.write(pickle.STACK_GLOBAL)
            else:
                self.write(pickle.GLOBAL +
                    (obj.__module__ + '\n' + obj.__name__ + '\n').decode("utf-8")
                )
            self.memoize(obj)
            return

        super().save_global(obj, name)
```

Please try that out.

**Comment by madeddy** [comment]
> likely needs your branch on tl works

Ah no. I tested with a clean version of current dev and master. Now with just the two fixes from above:

```bash
Error while decompiling /home/olli/.xlib/RPG/_test/OurBrightDays-0.1.3-pc/game/tl/english/scripts/00parts/01arrival/03script/script.rpyc:
Traceback (most recent call last):
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 218, in worker
return extract_translations(filename, args.language)
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 177, in extract_translations
return pickle_safe_dumps(translator.dialogue), translator.strings
File "/home/olli/Code/Git/unrpyc/decompiler/renpycompat.py", line 168, in pickle_safe_dumps
return magic.safe_dumps(buffer)
File "/home/olli/Code/Git/unrpyc/decompiler/magic.py", line 639, in safe_dumps
SafePickler(file, protocol).dump(obj)
File "/usr/lib/python3.10/pickle.py", line 487, in dump
self.save(obj)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 932, in save_list
self._batch_appends(obj)
File "/usr/lib/python3.10/pickle.py", line 959, in _batch_appends
save(tmp[0])
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
save(state)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
save(state)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
self._batch_setitems(obj.items())
File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
save(v)
File "/usr/lib/python3.10/pickle.py", line 603, in save
self.save_reduce(obj=obj, *rv)
File "/usr/lib/python3.10/pickle.py", line 691, in save_reduce
save(func)
File "/usr/lib/python3.10/pickle.py", line 560, in save
f(self, obj)  # Call unbound method with explicit self
File "/usr/lib/python3.10/pickle.py", line 1129, in save_type
return self.save_global(obj)
File "/home/olli/Code/Git/unrpyc/decompiler/magic.py", line 555, in save_global
super().save_global(obj, name)
File "/usr/lib/python3.10/pickle.py", line 1071, in save_global
raise PicklingError(
_pickle.PicklingError: Can't pickle <class '__builtin__.oldset'>: it's not found as __builtin__.oldset
```

**Comment by CensoredUsername** [comment]
Huh. I tested it with the files you posted and couldn't reproduce the error to begin with (that said, the errors were fairly obvious when I looked at it).

>_pickle.PicklingError: Can't pickle <class '__builtin__.oldset'>: it's not found as __builtin__.oldset

Oh bloody hell, need to add a __reduce__ impl to oldset/oldfrozenset as well.

**Comment by CensoredUsername** [comment]
Does this fix it (in renpycompat.py):

```python
class oldset(set):
    __module__ = "__builtin__"

    def __reduce__(self):
        cls, args, state = super().__reduce__()
        return (set, args, state)
```

```python
class oldfrozenset(frozenset):
    __module__ = "__builtin__"

    def __reduce__(self):
        cls, args, state = super().__reduce__()
        return (frozenset, args, state)
```

**Comment by madeddy** [comment]
Looks like that did it. Thanks!
Will test some with it like this and get back to you here.

**Comment by CensoredUsername** [comment]
>Removed also the pack parameter from save_global as i figured its unneeded.

It's in there due to python 2, where that is the signature of the method it's overriding. Strangely nothing there uses it either, but it can't hurt for compat to keep it in.

**Comment by madeddy** [comment]
Yes, i figured. With unneeded i meant py3 and i thought we need maybe a version switch for the diff py versions, as py3 does not have the pack para anymore.

**Comment by CensoredUsername** [comment]
Should be in dev now.
