### ISSUE TITLE
Errors during desobfuscation

### ISSUE THREAD

**Issue by Gouvernathor** [CensoredUsername/unrpyc#233]
These seem not to be unrpyc just failing because the file is too obfuscated, but just having an internal bug.
```
Error while decompiling C:\Users\Armise\Desktop\Visual Novels Workspace\Innocent_Witches-0-11-alpha-pc\game\scripts\plot\act_2_new\chapter_2\unforgettable_night_quest.rpyc:
Traceback (most recent call last):
  File "C:\Users\Armise\Desktop\git temp\unrpyc\deobfuscate.py", line 305, in read_ast
    data, stmts, d = try_decrypt_section(raw_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Armise\Desktop\git temp\unrpyc\deobfuscate.py", line 345, in try_decrypt_section
    raise ValueError("\n".join(diagnosis))
ValueError: performed a round of decrypt_zlib
Did not know how to decrypt data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Armise\Desktop\git temp\unrpyc\unrpyc.py", line 246, in worker_common
    decompile_rpyc(
  File "C:\Users\Armise\Desktop\git temp\unrpyc\unrpyc.py", line 190, in decompile_rpyc
    ast = get_ast(input_filename, try_harder, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Armise\Desktop\git temp\unrpyc\unrpyc.py", line 164, in get_ast
    ast = deobfuscate.read_ast(in_file, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Armise\Desktop\git temp\unrpyc\deobfuscate.py", line 307, in read_ast
    diagnosis.append(e.message)
                     ^^^^^^^^^
AttributeError: 'ValueError' object has no attribute 'message'
```

**Comment by CensoredUsername** [comment]
Probably python3 porting residue. Thanks for the report!

**Comment by CensoredUsername** [comment]
Also fixed in dev!
