### ISSUE TITLE
Doesn't work on Python 3.12

### ISSUE THREAD

**Issue by ark-1** [CensoredUsername/unrpyc#236]
Works fine on 3.11.

```
> python3.12 .../unrpyc/unrpyc.py --help

Traceback (most recent call last):
  File ".../unrpyc/unrpyc.py", line 53, in <module>
    import decompiler
  File ".../unrpyc/decompiler/__init__.py", line 30, in <module>
    magic.fake_package("renpy")
  File ".../unrpyc/decompiler/magic.py", line 643, in fake_package
    return __import__(name)
           ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'renpy'
```

I think the root cause is the change in `sys.meta_path` behavior: https://docs.python.org/3/library/sys.html#sys.meta_path

**Comment by ark-1** [comment]
Oh shit, I had the old version, sorry
