### ISSUE TITLE
Decompiled file crash

### ISSUE THREAD

**Issue by amber-stone** [CensoredUsername/unrpyc#61]
Traceback (most recent call last):
  File "renpy\execution.py", line 408, in run
    node.execute()
  File "renpy\ast.py", line 1151, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy\ast.py", line 1036, in show_imspec
    atl=atl)
  File "renpy\exports.py", line 647, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "renpy\display\core.py", line 975, in add
    thing._show()
  File "renpy\display\transform.py", line 964, in _show
    super(ATLTransform, self)._show()
  File "renpy\display\transform.py", line 948, in _show
    self.update_state()
  File "renpy\display\transform.py", line 806, in update_state
    fr = self.function(self, self.st, self.at)
  File "renpy\atl.py", line 483, in execute
    block = self.compile()
  File "renpy\atl.py", line 451, in compile
    block = self.atl.compile(self.context)
  File "renpy\atl.py", line 624, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "renpy\atl.py", line 871, in compile
    values = [ ctx.eval(i) for i in exprs ]
  File "renpy\atl.py", line 223, in eval
    return eval(expr, renpy.store.__dict__, self.context) #@UndefinedVariable
  File "<string>", line 1, in <module>
NameError: name 'knot' is not defined
code:                         linear 3.0 align knot (0.0, .33) knot (1.0, .66) knot (0.0, 0.0) zoom 1.0
RenPy version: 1749

**Comment by CensoredUsername** [comment]
Yeah I'm going to need a bit more information on this one. The only thing which tells me is that on a certain line of the script the term "knot" was undefined which as far as I know is a ren'py keyword. Are you sure you are using the right ren'py version?

Alternatively to figure out the problem I'd need a copy of the file on which it failed.

**Comment by amber-stone** [comment]
Solve error by removing extra knot keyword
Code must be:  linear 3.0 align (0.0, .33) knot (1.0, .66) knot (0.0, 0.0) zoom 1.0
So decompiler added extra 'knot' keyword or lost align argument

**Comment by CensoredUsername** [comment]
That is what I see as well, but I can't find any bug in the code which would result in either of those cases. Having access to the original .rpyc file would allow me to reproduce it and debug what's going wrong.

**Comment by amber-stone** [comment]
sent you script by email

**Comment by CensoredUsername** [comment]
Thanks! A fix for your problem should be available on the dev branch.

**Comment by amber-stone** [comment]
Thanks for fix, now all fine.
